<a href="https://colab.research.google.com/github/pawara101/tensor-flow/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this Notebook cover fundamental concepts of TensorFlow.
More specifically we are going to cover"
* Intro to tensors
* Getting information from tensors
* Manipulate tensors
* Tensors & Numpy
* use `tf.function`
* use GPU and TPU

In [ ]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.15.0


In [ ]:
## Creatinf tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# check the number of dimensions of a tensor
scalar.ndim

0

In [ ]:
# Create a vector
vector = tf.constant(([10,7]))
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
matrix = tf.constant([[10,7],
                      [6,4]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 6,  4]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
matrix.shape

TensorShape([2, 2])

In [ ]:
## Create another matrix
another_matrix = tf.constant([[10.,7.],
                              [3.,2.],
                              [8.,9.]],dtype=tf.float16) ## Specify datatypes

print(another_matrix)

print("Dimensions :",another_matrix.ndim)

tf.Tensor(
[[10.  7.]
 [ 3.  2.]
 [ 8.  9.]], shape=(3, 2), dtype=float16)
Dimensions : 2


In [ ]:
## Lets create a tensor
tensor = tf.constant([[[1,2,3],
                      [4,5,6]],
                      [[7,8,9],
                      [10,11,12]],
                      [[13,14,15],
                      [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

### Createing tensors with `tf.variable`

In [ ]:
# create the same tensor with tf.Variable

changable_tensor  = tf.Variable([10,7])
unchangable_tensor = tf.constant([10,7])
changable_tensor,unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# Let's try change one of the elements
# changable_tensor[0] = 8
# try .assign()
changable_tensor[0].assign(8)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([8, 7], dtype=int32)>

In [ ]:
# Lets try unchangable
unchangable_tensor[0].assign(56)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

## Create Random Tensors.

In [ ]:
## create two random tensors
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [ ]:
random_2 = tf.random.Generator.from_seed(42).normal(shape=(3,2))
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [ ]:
random_1,random_2,random_1==random_2 ## They are equal

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the order of elements in a tensors
* use `tf.random.shuffle`

In [ ]:
## Shuffle a tensor
not_shuffled = tf.constant([[10,7],
                           [3,4],
                           [2,5]])
## shuffle non-shuffle tensor
tf.random.shuffle(not_shuffled,seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

**Exercise :** Read Tf random seed generation
`tf.random.Generator` uses to to produce different results.


In [ ]:
g1 = tf.random.Generator.from_seed(1)
print(g1.normal(shape=[2, 3]))

tf.Tensor(
[[ 0.43842274 -0.53439844 -0.07710262]
 [ 1.5658046  -0.1012345  -0.2744976 ]], shape=(2, 3), dtype=float32)


In [ ]:
g2 = tf.random.get_global_generator()
print(g2.normal(shape=[2, 3]))

tf.Tensor(
[[ 1.1754577   2.7430997  -0.24421544]
 [-1.0367228   0.30793983  0.45924687]], shape=(2, 3), dtype=float32)


In [ ]:
g = tf.random.Generator.from_seed(42)
print(g.normal([]))
print(g.normal([]))
g.reset_from_seed(1)
print(g.normal([]))

tf.Tensor(-0.7565803, shape=(), dtype=float32)
tf.Tensor(0.7093353, shape=(), dtype=float32)
tf.Tensor(0.43842274, shape=(), dtype=float32)


In [ ]:
g = tf.random.Generator.from_seed(42)
print(g.normal([]))
print(g.normal([]))
g.reset_from_seed(42)
print(g.normal([]))

tf.Tensor(-0.7565803, shape=(), dtype=float32)
tf.Tensor(0.7093353, shape=(), dtype=float32)
tf.Tensor(-0.7565803, shape=(), dtype=float32)


In [ ]:
##
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled,seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

### Other ways to make tensors

In [ ]:
## Create ones tensor
tf.ones([10,3])

<tf.Tensor: shape=(10, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [ ]:
## Zeros
tf.zeros(shape=(2,6))

<tf.Tensor: shape=(2, 6), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]], dtype=float32)>

### Turn Numpy array into tensors

In [ ]:
## Turn Numpy into a tensor
import numpy as np
numpy_A = np.arange(1,25,dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A = tf.constant(numpy_A,shape=(3,8))
B = tf.constant(numpy_A)
A,B

(<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
 array([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

### Getting information from tensors.
When dealing with tensors you check these;
* Shape
* Rank
* Axis
* Size

In [38]:
# Create a Rank 4 Tensor
rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [39]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [40]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [42]:
# Get Various attributes of our tensor.
print("Datatype of every element: ",rank_4_tensor.dtype)
print("Number of dimensions (rank) :",rank_4_tensor.ndim)
print("Shape of tensor :",rank_4_tensor.shape)
print("Elements along 0 Axis :",rank_4_tensor.shape[0])
print("Elements along last Axis :",rank_4_tensor.shape[-1])
print("Total number of elements in our tensor :",tf.size(rank_4_tensor))
print("Total number of elements in our tensor :",tf.size(rank_4_tensor).numpy())

Datatype of every element:  <dtype: 'float32'>
Number of dimensions (rank) : 4
Shape of tensor : (2, 3, 4, 5)
Elements along 0 Axis : 2
Elements along last Axis : 5
Total number of elements in our tensor : tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in our tensor : 120
